[F2F-734] Updates to reflect IPV_F2F_CRI_VC_CONSUMED event sending nameParts
alphagov/di-ipvreturn-api pull request #28
Opened 2023-06-09 09:18 UTC by Caitlin-cooling

## Proposed changes
As agreed [here](https://gds.slack.com/archives/C04N9K8GZDX/p1685821801352049?thread_ts=1685707211.898849&cid=C04N9K8GZDX) `nameParts` are now going to be sent in the `IPV_F2F_CRI_VC_CONSUMED` event. Proposed changes as detailed in the ticket include the update of `PostEventProcessor`  and `SessionEventProcessor` to handle the `nameParts` and include them in the call to govNotify

### What changed
- `PostEventProcessor` updated to write the `nameParts` in to the db when `IPV_F2F_CRI_VC_CONSUMED` event is triggered
- `SessionEventProcessor` updated to send the `nameParts` to govNotify 
- `SessionEvent` type updated to include `nameParts`
- `PersonalIdentityUtils.getName` copied over from f2f to extract first and last name from the `nameParts` array

### Why did it change
We need to save `nameParts` from the `IPV_F2F_CRI_VC_CONSUMED` event in the db so that it can later be extracted and the users name can be included in the email to them.

## Checklists

### PII logging

- [x] Verified that no PII data is being logged

### Environment variables or secrets

- [ x] No environment variables or secrets were added or changed

2023-06-09 13:16 UTC, Caitlin-cooling commented on src/tests/unit/services/SessionEventProcessor.test.ts
> +		expect(mockIprService.sendToGovNotify).toHaveBeenCalledWith({
Add test for scenario where nameParts is not given/correct

2023-06-09 13:23 UTC, Caitlin-cooling commented
TODO dev test this against ACs and attach screenshots of logs once I have AWS access

2023-06-09 13:51 UTC, Caitlin-cooling commented on src/tests/unit/services/SessionEventProcessor.test.ts
> +		expect(mockIprService.sendToGovNotify).toHaveBeenCalledWith({
Done

2023-06-19 12:09 UTC, Caitlin-cooling commented
@richa-misra now that the event contains PII when we log the record [here](https://github.com/alphagov/di-ipvreturn-api/blob/F2F-734/src/PostEventHandler.ts#L25) we are logging PII. 

How would you normally handle this? I can see that the log would be helpful for debugging so do we have a pattern for obfuscating the data maybe?

2023-06-19 19:52 UTC, hemavana requested changes

2023-06-20 17:16 UTC, richa-misra commented
> @richa-misra now that the event contains PII when we log the record [here](https://github.com/alphagov/di-ipvreturn-api/blob/F2F-734/src/PostEventHandler.ts#L25) we are logging PII.
> 
> How would you normally handle this? I can see that the log would be helpful for debugging so do we have a pattern for obfuscating the data maybe?

Hi @Caitlin-cooling good ques, yes we would need to implement a hashing pattern for PII fields across the logs. Instead of logging the entire SQS record, could you try logging the PII fields by replacing their actual value with its hash instead when logging it pls, something like this 

`****** (${Md5.hashStr(value.toString())})`

2023-06-21 08:20 UTC, Caitlin-cooling commented on src/models/SessionReturnRecord.ts
> +    nameParts?: NamePart[];
Done!

2023-06-21 17:02 UTC, merged